### ISSUE TITLE
Not working on Wayland, Linux

### ISSUE THREAD

**Issue by ida-lovelace** [adryzz/midi-keypad#2]
Hey there! I'm running this software on the Sway WM under linux, and it seems to not work. I've installed the android app, enabled midi both in the android settings and on osu lazer and then try to tap, but it doesn't work. What could the culprit be?

**Comment by adryzz** [comment]
well... i run sway too and it works just fine there

it's definitely not a wayland thing, that has nothing to do with it.

 are you using pipewire? do you have pipewire-alsa, pipewire-jack or pipewire-pulse?

**Comment by ida-lovelace** [comment]
Yeah, using pipewire as latency's better than pulseaudio.

**Comment by adryzz** [comment]
> Yeah, using pipewire as latency's better than pulseaudio.

yeah but pulse doesnt even support MIDI so thats a no-brainer.

anyway, have you set your osu! keybinds? can you try seeing if another app can receive the midi input?

**Comment by ida-lovelace** [comment]
My keybinds are set to z and x. Am I supposed to use different ones? What other app can I use to test midi input? For reference, I connect the phone to my laptop, turn on midi in the usb settings, it detects my device as android usb peripheral port, I press start, also turn on midi in lazer settings, try to tap in game but nothing happens.

**Comment by adryzz** [comment]
yeah you need to set your keybinds to use the MIDI keys

**Comment by ida-lovelace** [comment]
K I finally figured it out, I had to go in the input settings, osu, left button and right button, and press the buttons on my phone. Its not quite self explanatory, but at least it works for me now. Thank you! Closing this issue.

**Comment by ida-lovelace** [comment]
Oh, one more thing, is using this on stable possible?

**Comment by adryzz** [comment]
nope, stable does not support MIDI input, for that you'd need a separate app on the pc (which is the whole thing this app was made to solve in the first place, *not* having anything to install on the PC)
